version: '3.8'

services:
  anonac:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anonaction2077
      POSTGRES_DB: anonac
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  pgdata:
